### ISSUE TITLE
Можно ли сделать сортировку лучше?

### ISSUE THREAD

**Issue by blmzv** [Artem-Brunov/SortableTable#2]
Мне кажется, с т.з. пользователя сортировка работает не совсем ожидаемо.

https://github.com/Artem-Brunov/SortableTable/blob/3e504b0e9df92a6f4905fcef0f719efa954c9e40/SortableTable/src/containers/App.js#L15

**Comment by Artem-Brunov** [comment]
Код сортировки уменьшил, а что не так с результатом работы?

**Comment by Artem-Brunov** [comment]
> Мне кажется, с т.з. пользователя сортировка работает не совсем ожидаемо.
> 
> https://github.com/Artem-Brunov/SortableTable/blob/3e504b0e9df92a6f4905fcef0f719efa954c9e40/SortableTable/src/containers/App.js#L15

Код сортировки уменьшил, а что не так с результатом работы?

**Comment by Artem-Brunov** [comment]
> Мне кажется, с т.з. пользователя сортировка работает не совсем ожидаемо.
> 
> https://github.com/Artem-Brunov/SortableTable/blob/3e504b0e9df92a6f4905fcef0f719efa954c9e40/SortableTable/src/containers/App.js#L15

Исправил результат работы, если имелось ввиду сортирование с учетом регистра.
