### ISSUE TITLE
Попробуй чуть поменять стиль написания кода

### ISSUE THREAD

**Issue by blmzv** [Artem-Brunov/SortableTable#3]
1. Использовать стрелочные функции и другие плюшки ES6
2. Использовать react-hooks
3. Не использовать let, а только const (не мутировать переменные)
4. Ставить везде где нужно «;»

**Comment by Artem-Brunov** [comment]
> 1. Использовать стрелочные функции и другие плюшки ES6
> 2. Использовать react-hooks
> 3. Не использовать let, а только const (не мутировать переменные)
> 4. Ставить везде где нужно «;»

Вы хотите, чтобы я использовал хуки вместо mapStateToProps и mapDispatchToProps?
